/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLockerRouteImport } from './routes/_authenticated/locker'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRosterRouteImport } from './routes/_authenticated/roster'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as LockerTokenRouteImport } from './routes/locker.$token'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthenticatedGameGameIdRouteImport } from './routes/_authenticated/game.$gameId'
import { Route as AuthenticatedGamesIndexRouteImport } from './routes/_authenticated/games.index'
import { Route as AuthenticatedGamesNewRouteImport } from './routes/_authenticated/games.new'
import { Route as AuthenticatedPlaysIndexRouteImport } from './routes/_authenticated/plays.index'
import { Route as AuthenticatedPlaysNewRouteImport } from './routes/_authenticated/plays.new'
import { Route as AuthenticatedReviewGameIdRouteImport } from './routes/_authenticated/review.$gameId'
import { Route as AuthenticatedStatsPlayersRouteImport } from './routes/_authenticated/stats.players'
import { Route as AuthenticatedStatsTeamRouteImport } from './routes/_authenticated/stats.team'
import { Route as AuthenticatedPlaysPlayIdIndexRouteImport } from './routes/_authenticated/plays.$playId.index'
import { Route as AuthenticatedPlaysPlayIdViewRouteImport } from './routes/_authenticated/plays.$playId.view'
import { Route as ApiPublicLockerTokenCalendarRouteImport } from './routes/api/public/locker.$token.calendar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLockerRoute = AuthenticatedLockerRouteImport.update({
  id: '/locker',
  path: '/locker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRosterRoute = AuthenticatedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LockerTokenRoute = LockerTokenRouteImport.update({
  id: '/locker/$token',
  path: '/locker/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGameGameIdRoute = AuthenticatedGameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesIndexRoute = AuthenticatedGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesNewRoute = AuthenticatedGamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaysIndexRoute = AuthenticatedPlaysIndexRouteImport.update({
  id: '/plays/',
  path: '/plays/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaysNewRoute = AuthenticatedPlaysNewRouteImport.update({
  id: '/plays/new',
  path: '/plays/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewGameIdRoute =
  AuthenticatedReviewGameIdRouteImport.update({
    id: '/review/$gameId',
    path: '/review/$gameId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatsPlayersRoute =
  AuthenticatedStatsPlayersRouteImport.update({
    id: '/stats/players',
    path: '/stats/players',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatsTeamRoute = AuthenticatedStatsTeamRouteImport.update({
  id: '/stats/team',
  path: '/stats/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaysPlayIdIndexRoute =
  AuthenticatedPlaysPlayIdIndexRouteImport.update({
    id: '/plays/$playId/',
    path: '/plays/$playId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaysPlayIdViewRoute =
  AuthenticatedPlaysPlayIdViewRouteImport.update({
    id: '/plays/$playId/view',
    path: '/plays/$playId/view',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicLockerTokenCalendarRoute =
  ApiPublicLockerTokenCalendarRouteImport.update({
    id: '/api/public/locker/$token/calendar',
    path: '/api/public/locker/$token/calendar',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/locker': typeof AuthenticatedLockerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/locker/$token': typeof LockerTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/game/$gameId': typeof AuthenticatedGameGameIdRoute
  '/games/new': typeof AuthenticatedGamesNewRoute
  '/plays/new': typeof AuthenticatedPlaysNewRoute
  '/review/$gameId': typeof AuthenticatedReviewGameIdRoute
  '/stats/players': typeof AuthenticatedStatsPlayersRoute
  '/stats/team': typeof AuthenticatedStatsTeamRoute
  '/games/': typeof AuthenticatedGamesIndexRoute
  '/plays/': typeof AuthenticatedPlaysIndexRoute
  '/plays/$playId/view': typeof AuthenticatedPlaysPlayIdViewRoute
  '/plays/$playId/': typeof AuthenticatedPlaysPlayIdIndexRoute
  '/api/public/locker/$token/calendar': typeof ApiPublicLockerTokenCalendarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/locker': typeof AuthenticatedLockerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/locker/$token': typeof LockerTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/game/$gameId': typeof AuthenticatedGameGameIdRoute
  '/games/new': typeof AuthenticatedGamesNewRoute
  '/plays/new': typeof AuthenticatedPlaysNewRoute
  '/review/$gameId': typeof AuthenticatedReviewGameIdRoute
  '/stats/players': typeof AuthenticatedStatsPlayersRoute
  '/stats/team': typeof AuthenticatedStatsTeamRoute
  '/games': typeof AuthenticatedGamesIndexRoute
  '/plays': typeof AuthenticatedPlaysIndexRoute
  '/plays/$playId/view': typeof AuthenticatedPlaysPlayIdViewRoute
  '/plays/$playId': typeof AuthenticatedPlaysPlayIdIndexRoute
  '/api/public/locker/$token/calendar': typeof ApiPublicLockerTokenCalendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/locker': typeof AuthenticatedLockerRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/roster': typeof AuthenticatedRosterRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/locker/$token': typeof LockerTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/game/$gameId': typeof AuthenticatedGameGameIdRoute
  '/_authenticated/games/new': typeof AuthenticatedGamesNewRoute
  '/_authenticated/plays/new': typeof AuthenticatedPlaysNewRoute
  '/_authenticated/review/$gameId': typeof AuthenticatedReviewGameIdRoute
  '/_authenticated/stats/players': typeof AuthenticatedStatsPlayersRoute
  '/_authenticated/stats/team': typeof AuthenticatedStatsTeamRoute
  '/_authenticated/games/': typeof AuthenticatedGamesIndexRoute
  '/_authenticated/plays/': typeof AuthenticatedPlaysIndexRoute
  '/_authenticated/plays/$playId/view': typeof AuthenticatedPlaysPlayIdViewRoute
  '/_authenticated/plays/$playId/': typeof AuthenticatedPlaysPlayIdIndexRoute
  '/api/public/locker/$token/calendar': typeof ApiPublicLockerTokenCalendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/locker'
    | '/profile'
    | '/roster'
    | '/settings'
    | '/invite/$token'
    | '/locker/$token'
    | '/share/$token'
    | '/game/$gameId'
    | '/games/new'
    | '/plays/new'
    | '/review/$gameId'
    | '/stats/players'
    | '/stats/team'
    | '/games/'
    | '/plays/'
    | '/plays/$playId/view'
    | '/plays/$playId/'
    | '/api/public/locker/$token/calendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/locker'
    | '/profile'
    | '/roster'
    | '/settings'
    | '/invite/$token'
    | '/locker/$token'
    | '/share/$token'
    | '/game/$gameId'
    | '/games/new'
    | '/plays/new'
    | '/review/$gameId'
    | '/stats/players'
    | '/stats/team'
    | '/games'
    | '/plays'
    | '/plays/$playId/view'
    | '/plays/$playId'
    | '/api/public/locker/$token/calendar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/locker'
    | '/_authenticated/profile'
    | '/_authenticated/roster'
    | '/_authenticated/settings'
    | '/invite/$token'
    | '/locker/$token'
    | '/share/$token'
    | '/_authenticated/game/$gameId'
    | '/_authenticated/games/new'
    | '/_authenticated/plays/new'
    | '/_authenticated/review/$gameId'
    | '/_authenticated/stats/players'
    | '/_authenticated/stats/team'
    | '/_authenticated/games/'
    | '/_authenticated/plays/'
    | '/_authenticated/plays/$playId/view'
    | '/_authenticated/plays/$playId/'
    | '/api/public/locker/$token/calendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LockerTokenRoute: typeof LockerTokenRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiPublicLockerTokenCalendarRoute: typeof ApiPublicLockerTokenCalendarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locker': {
      id: '/_authenticated/locker'
      path: '/locker'
      fullPath: '/locker'
      preLoaderRoute: typeof AuthenticatedLockerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster': {
      id: '/_authenticated/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedRosterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locker/$token': {
      id: '/locker/$token'
      path: '/locker/$token'
      fullPath: '/locker/$token'
      preLoaderRoute: typeof LockerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/game/$gameId': {
      id: '/_authenticated/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof AuthenticatedGameGameIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/': {
      id: '/_authenticated/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AuthenticatedGamesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/new': {
      id: '/_authenticated/games/new'
      path: '/games/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof AuthenticatedGamesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plays/': {
      id: '/_authenticated/plays/'
      path: '/plays'
      fullPath: '/plays/'
      preLoaderRoute: typeof AuthenticatedPlaysIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plays/new': {
      id: '/_authenticated/plays/new'
      path: '/plays/new'
      fullPath: '/plays/new'
      preLoaderRoute: typeof AuthenticatedPlaysNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/$gameId': {
      id: '/_authenticated/review/$gameId'
      path: '/review/$gameId'
      fullPath: '/review/$gameId'
      preLoaderRoute: typeof AuthenticatedReviewGameIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats/players': {
      id: '/_authenticated/stats/players'
      path: '/stats/players'
      fullPath: '/stats/players'
      preLoaderRoute: typeof AuthenticatedStatsPlayersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats/team': {
      id: '/_authenticated/stats/team'
      path: '/stats/team'
      fullPath: '/stats/team'
      preLoaderRoute: typeof AuthenticatedStatsTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plays/$playId/': {
      id: '/_authenticated/plays/$playId/'
      path: '/plays/$playId'
      fullPath: '/plays/$playId/'
      preLoaderRoute: typeof AuthenticatedPlaysPlayIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plays/$playId/view': {
      id: '/_authenticated/plays/$playId/view'
      path: '/plays/$playId/view'
      fullPath: '/plays/$playId/view'
      preLoaderRoute: typeof AuthenticatedPlaysPlayIdViewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/locker/$token/calendar': {
      id: '/api/public/locker/$token/calendar'
      path: '/api/public/locker/$token/calendar'
      fullPath: '/api/public/locker/$token/calendar'
      preLoaderRoute: typeof ApiPublicLockerTokenCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLockerRoute: typeof AuthenticatedLockerRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRosterRoute: typeof AuthenticatedRosterRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedGameGameIdRoute: typeof AuthenticatedGameGameIdRoute
  AuthenticatedGamesNewRoute: typeof AuthenticatedGamesNewRoute
  AuthenticatedPlaysNewRoute: typeof AuthenticatedPlaysNewRoute
  AuthenticatedReviewGameIdRoute: typeof AuthenticatedReviewGameIdRoute
  AuthenticatedStatsPlayersRoute: typeof AuthenticatedStatsPlayersRoute
  AuthenticatedStatsTeamRoute: typeof AuthenticatedStatsTeamRoute
  AuthenticatedGamesIndexRoute: typeof AuthenticatedGamesIndexRoute
  AuthenticatedPlaysIndexRoute: typeof AuthenticatedPlaysIndexRoute
  AuthenticatedPlaysPlayIdViewRoute: typeof AuthenticatedPlaysPlayIdViewRoute
  AuthenticatedPlaysPlayIdIndexRoute: typeof AuthenticatedPlaysPlayIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLockerRoute: AuthenticatedLockerRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRosterRoute: AuthenticatedRosterRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedGameGameIdRoute: AuthenticatedGameGameIdRoute,
  AuthenticatedGamesNewRoute: AuthenticatedGamesNewRoute,
  AuthenticatedPlaysNewRoute: AuthenticatedPlaysNewRoute,
  AuthenticatedReviewGameIdRoute: AuthenticatedReviewGameIdRoute,
  AuthenticatedStatsPlayersRoute: AuthenticatedStatsPlayersRoute,
  AuthenticatedStatsTeamRoute: AuthenticatedStatsTeamRoute,
  AuthenticatedGamesIndexRoute: AuthenticatedGamesIndexRoute,
  AuthenticatedPlaysIndexRoute: AuthenticatedPlaysIndexRoute,
  AuthenticatedPlaysPlayIdViewRoute: AuthenticatedPlaysPlayIdViewRoute,
  AuthenticatedPlaysPlayIdIndexRoute: AuthenticatedPlaysPlayIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InviteTokenRoute: InviteTokenRoute,
  LockerTokenRoute: LockerTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiPublicLockerTokenCalendarRoute: ApiPublicLockerTokenCalendarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
