/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedBoardRouteImport } from './routes/_authenticated/board'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedKpiRouteImport } from './routes/_authenticated/kpi'
import { Route as AuthenticatedLaunchQaRouteImport } from './routes/_authenticated/launch-qa'
import { Route as AuthenticatedLockerRouteImport } from './routes/_authenticated/locker'
import { Route as AuthenticatedLockerroomRouteImport } from './routes/_authenticated/lockerroom'
import { Route as AuthenticatedMembershipRouteImport } from './routes/_authenticated/membership'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRosterRouteImport } from './routes/_authenticated/roster'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as CoachUsernameRouteImport } from './routes/coach.$username'
import { Route as DrillsDrillIdRouteImport } from './routes/drills.$drillId'
import { Route as GameReportTokenRouteImport } from './routes/game-report.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryPlayIdRouteImport } from './routes/library.$playId'
import { Route as LockerTokenRouteImport } from './routes/locker.$token'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthenticatedDrillsIndexRouteImport } from './routes/_authenticated/drills.index'
import { Route as AuthenticatedDrillsNewRouteImport } from './routes/_authenticated/drills.new'
import { Route as AuthenticatedFilmIndexRouteImport } from './routes/_authenticated/film.index'
import { Route as AuthenticatedFilmJobIdRouteImport } from './routes/_authenticated/film.$jobId'
import { Route as AuthenticatedFilmNewRouteImport } from './routes/_authenticated/film.new'
import { Route as AuthenticatedGameGameIdRouteImport } from './routes/_authenticated/game.$gameId'
import { Route as AuthenticatedGamesIndexRouteImport } from './routes/_authenticated/games.index'
import { Route as AuthenticatedGamesNewRouteImport } from './routes/_authenticated/games.new'
import { Route as AuthenticatedPlaysIndexRouteImport } from './routes/_authenticated/plays.index'
import { Route as AuthenticatedPlaysNewRouteImport } from './routes/_authenticated/plays.new'
import { Route as AuthenticatedPracticeIndexRouteImport } from './routes/_authenticated/practice.index'
import { Route as AuthenticatedPracticePlanIdRouteImport } from './routes/_authenticated/practice.$planId'
import { Route as AuthenticatedReviewGameIdRouteImport } from './routes/_authenticated/review.$gameId'
import { Route as AuthenticatedStatsIndexRouteImport } from './routes/_authenticated/stats.index'
import { Route as AuthenticatedStatsPlayersRouteImport } from './routes/_authenticated/stats.players'
import { Route as AuthenticatedStatsTeamRouteImport } from './routes/_authenticated/stats.team'
import { Route as SharePlayTokenRouteImport } from './routes/share.play.$token'
import { Route as AuthenticatedPlaysPlayIdIndexRouteImport } from './routes/_authenticated/plays.$playId.index'
import { Route as AuthenticatedPlaysPlayIdViewRouteImport } from './routes/_authenticated/plays.$playId.view'
import { Route as ApiPublicCronDailyRouteImport } from './routes/api/public/cron.daily'
import { Route as ApiPublicFilmClaimRouteImport } from './routes/api/public/film/claim'
import { Route as ApiPublicFilmFailRouteImport } from './routes/api/public/film/fail'
import { Route as ApiPublicFilmResultsRouteImport } from './routes/api/public/film/results'
import { Route as ApiPublicFilmStatusRouteImport } from './routes/api/public/film/status'
import { Route as ApiPublicSquareWebhookRouteImport } from './routes/api/public/square.webhook'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe.webhook'
import { Route as ApiPublicGoogleCalendarCallbackRouteImport } from './routes/api/public/google.calendar.callback'
import { Route as ApiPublicLockerTokenCalendarRouteImport } from './routes/api/public/locker.$token.calendar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoardRoute = AuthenticatedBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKpiRoute = AuthenticatedKpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaunchQaRoute = AuthenticatedLaunchQaRouteImport.update({
  id: '/launch-qa',
  path: '/launch-qa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLockerRoute = AuthenticatedLockerRouteImport.update({
  id: '/locker',
  path: '/locker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLockerroomRoute = AuthenticatedLockerroomRouteImport.update({
  id: '/lockerroom',
  path: '/lockerroom',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembershipRoute = AuthenticatedMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRosterRoute = AuthenticatedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CoachUsernameRoute = CoachUsernameRouteImport.update({
  id: '/coach/$username',
  path: '/coach/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillsDrillIdRoute = DrillsDrillIdRouteImport.update({
  id: '/drills/$drillId',
  path: '/drills/$drillId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameReportTokenRoute = GameReportTokenRouteImport.update({
  id: '/game-report/$token',
  path: '/game-report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryPlayIdRoute = LibraryPlayIdRouteImport.update({
  id: '/library/$playId',
  path: '/library/$playId',
  getParentRoute: () => rootRouteImport,
} as any)
const LockerTokenRoute = LockerTokenRouteImport.update({
  id: '/locker/$token',
  path: '/locker/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDrillsIndexRoute =
  AuthenticatedDrillsIndexRouteImport.update({
    id: '/drills/',
    path: '/drills/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDrillsNewRoute = AuthenticatedDrillsNewRouteImport.update({
  id: '/drills/new',
  path: '/drills/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilmIndexRoute = AuthenticatedFilmIndexRouteImport.update({
  id: '/film/',
  path: '/film/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilmJobIdRoute = AuthenticatedFilmJobIdRouteImport.update({
  id: '/film/$jobId',
  path: '/film/$jobId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilmNewRoute = AuthenticatedFilmNewRouteImport.update({
  id: '/film/new',
  path: '/film/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGameGameIdRoute = AuthenticatedGameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesIndexRoute = AuthenticatedGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesNewRoute = AuthenticatedGamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaysIndexRoute = AuthenticatedPlaysIndexRouteImport.update({
  id: '/plays/',
  path: '/plays/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaysNewRoute = AuthenticatedPlaysNewRouteImport.update({
  id: '/plays/new',
  path: '/plays/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeIndexRoute =
  AuthenticatedPracticeIndexRouteImport.update({
    id: '/practice/',
    path: '/practice/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticePlanIdRoute =
  AuthenticatedPracticePlanIdRouteImport.update({
    id: '/practice/$planId',
    path: '/practice/$planId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewGameIdRoute =
  AuthenticatedReviewGameIdRouteImport.update({
    id: '/review/$gameId',
    path: '/review/$gameId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatsIndexRoute = AuthenticatedStatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsPlayersRoute =
  AuthenticatedStatsPlayersRouteImport.update({
    id: '/stats/players',
    path: '/stats/players',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatsTeamRoute = AuthenticatedStatsTeamRouteImport.update({
  id: '/stats/team',
  path: '/stats/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SharePlayTokenRoute = SharePlayTokenRouteImport.update({
  id: '/share/play/$token',
  path: '/share/play/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlaysPlayIdIndexRoute =
  AuthenticatedPlaysPlayIdIndexRouteImport.update({
    id: '/plays/$playId/',
    path: '/plays/$playId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaysPlayIdViewRoute =
  AuthenticatedPlaysPlayIdViewRouteImport.update({
    id: '/plays/$playId/view',
    path: '/plays/$playId/view',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronDailyRoute = ApiPublicCronDailyRouteImport.update({
  id: '/api/public/cron/daily',
  path: '/api/public/cron/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFilmClaimRoute = ApiPublicFilmClaimRouteImport.update({
  id: '/api/public/film/claim',
  path: '/api/public/film/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFilmFailRoute = ApiPublicFilmFailRouteImport.update({
  id: '/api/public/film/fail',
  path: '/api/public/film/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFilmResultsRoute = ApiPublicFilmResultsRouteImport.update({
  id: '/api/public/film/results',
  path: '/api/public/film/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFilmStatusRoute = ApiPublicFilmStatusRouteImport.update({
  id: '/api/public/film/status',
  path: '/api/public/film/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSquareWebhookRoute = ApiPublicSquareWebhookRouteImport.update({
  id: '/api/public/square/webhook',
  path: '/api/public/square/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleCalendarCallbackRoute =
  ApiPublicGoogleCalendarCallbackRouteImport.update({
    id: '/api/public/google/calendar/callback',
    path: '/api/public/google/calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLockerTokenCalendarRoute =
  ApiPublicLockerTokenCalendarRouteImport.update({
    id: '/api/public/locker/$token/calendar',
    path: '/api/public/locker/$token/calendar',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/board': typeof AuthenticatedBoardRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/kpi': typeof AuthenticatedKpiRoute
  '/launch-qa': typeof AuthenticatedLaunchQaRoute
  '/locker': typeof AuthenticatedLockerRoute
  '/lockerroom': typeof AuthenticatedLockerroomRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/coach/$username': typeof CoachUsernameRoute
  '/drills/$drillId': typeof DrillsDrillIdRoute
  '/game-report/$token': typeof GameReportTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/library/$playId': typeof LibraryPlayIdRoute
  '/locker/$token': typeof LockerTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/library/': typeof LibraryIndexRoute
  '/drills/new': typeof AuthenticatedDrillsNewRoute
  '/film/$jobId': typeof AuthenticatedFilmJobIdRoute
  '/film/new': typeof AuthenticatedFilmNewRoute
  '/game/$gameId': typeof AuthenticatedGameGameIdRoute
  '/games/new': typeof AuthenticatedGamesNewRoute
  '/plays/new': typeof AuthenticatedPlaysNewRoute
  '/practice/$planId': typeof AuthenticatedPracticePlanIdRoute
  '/review/$gameId': typeof AuthenticatedReviewGameIdRoute
  '/stats/players': typeof AuthenticatedStatsPlayersRoute
  '/stats/team': typeof AuthenticatedStatsTeamRoute
  '/share/play/$token': typeof SharePlayTokenRoute
  '/drills/': typeof AuthenticatedDrillsIndexRoute
  '/film/': typeof AuthenticatedFilmIndexRoute
  '/games/': typeof AuthenticatedGamesIndexRoute
  '/plays/': typeof AuthenticatedPlaysIndexRoute
  '/practice/': typeof AuthenticatedPracticeIndexRoute
  '/stats/': typeof AuthenticatedStatsIndexRoute
  '/plays/$playId/view': typeof AuthenticatedPlaysPlayIdViewRoute
  '/api/public/cron/daily': typeof ApiPublicCronDailyRoute
  '/api/public/film/claim': typeof ApiPublicFilmClaimRoute
  '/api/public/film/fail': typeof ApiPublicFilmFailRoute
  '/api/public/film/results': typeof ApiPublicFilmResultsRoute
  '/api/public/film/status': typeof ApiPublicFilmStatusRoute
  '/api/public/square/webhook': typeof ApiPublicSquareWebhookRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/plays/$playId/': typeof AuthenticatedPlaysPlayIdIndexRoute
  '/api/public/google/calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/locker/$token/calendar': typeof ApiPublicLockerTokenCalendarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/board': typeof AuthenticatedBoardRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/kpi': typeof AuthenticatedKpiRoute
  '/launch-qa': typeof AuthenticatedLaunchQaRoute
  '/locker': typeof AuthenticatedLockerRoute
  '/lockerroom': typeof AuthenticatedLockerroomRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/coach/$username': typeof CoachUsernameRoute
  '/drills/$drillId': typeof DrillsDrillIdRoute
  '/game-report/$token': typeof GameReportTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/library/$playId': typeof LibraryPlayIdRoute
  '/locker/$token': typeof LockerTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/library': typeof LibraryIndexRoute
  '/drills/new': typeof AuthenticatedDrillsNewRoute
  '/film/$jobId': typeof AuthenticatedFilmJobIdRoute
  '/film/new': typeof AuthenticatedFilmNewRoute
  '/game/$gameId': typeof AuthenticatedGameGameIdRoute
  '/games/new': typeof AuthenticatedGamesNewRoute
  '/plays/new': typeof AuthenticatedPlaysNewRoute
  '/practice/$planId': typeof AuthenticatedPracticePlanIdRoute
  '/review/$gameId': typeof AuthenticatedReviewGameIdRoute
  '/stats/players': typeof AuthenticatedStatsPlayersRoute
  '/stats/team': typeof AuthenticatedStatsTeamRoute
  '/share/play/$token': typeof SharePlayTokenRoute
  '/drills': typeof AuthenticatedDrillsIndexRoute
  '/film': typeof AuthenticatedFilmIndexRoute
  '/games': typeof AuthenticatedGamesIndexRoute
  '/plays': typeof AuthenticatedPlaysIndexRoute
  '/practice': typeof AuthenticatedPracticeIndexRoute
  '/stats': typeof AuthenticatedStatsIndexRoute
  '/plays/$playId/view': typeof AuthenticatedPlaysPlayIdViewRoute
  '/api/public/cron/daily': typeof ApiPublicCronDailyRoute
  '/api/public/film/claim': typeof ApiPublicFilmClaimRoute
  '/api/public/film/fail': typeof ApiPublicFilmFailRoute
  '/api/public/film/results': typeof ApiPublicFilmResultsRoute
  '/api/public/film/status': typeof ApiPublicFilmStatusRoute
  '/api/public/square/webhook': typeof ApiPublicSquareWebhookRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/plays/$playId': typeof AuthenticatedPlaysPlayIdIndexRoute
  '/api/public/google/calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/locker/$token/calendar': typeof ApiPublicLockerTokenCalendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/board': typeof AuthenticatedBoardRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/kpi': typeof AuthenticatedKpiRoute
  '/_authenticated/launch-qa': typeof AuthenticatedLaunchQaRoute
  '/_authenticated/locker': typeof AuthenticatedLockerRoute
  '/_authenticated/lockerroom': typeof AuthenticatedLockerroomRoute
  '/_authenticated/membership': typeof AuthenticatedMembershipRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/roster': typeof AuthenticatedRosterRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/coach/$username': typeof CoachUsernameRoute
  '/drills/$drillId': typeof DrillsDrillIdRoute
  '/game-report/$token': typeof GameReportTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/library/$playId': typeof LibraryPlayIdRoute
  '/locker/$token': typeof LockerTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/library/': typeof LibraryIndexRoute
  '/_authenticated/drills/new': typeof AuthenticatedDrillsNewRoute
  '/_authenticated/film/$jobId': typeof AuthenticatedFilmJobIdRoute
  '/_authenticated/film/new': typeof AuthenticatedFilmNewRoute
  '/_authenticated/game/$gameId': typeof AuthenticatedGameGameIdRoute
  '/_authenticated/games/new': typeof AuthenticatedGamesNewRoute
  '/_authenticated/plays/new': typeof AuthenticatedPlaysNewRoute
  '/_authenticated/practice/$planId': typeof AuthenticatedPracticePlanIdRoute
  '/_authenticated/review/$gameId': typeof AuthenticatedReviewGameIdRoute
  '/_authenticated/stats/players': typeof AuthenticatedStatsPlayersRoute
  '/_authenticated/stats/team': typeof AuthenticatedStatsTeamRoute
  '/share/play/$token': typeof SharePlayTokenRoute
  '/_authenticated/drills/': typeof AuthenticatedDrillsIndexRoute
  '/_authenticated/film/': typeof AuthenticatedFilmIndexRoute
  '/_authenticated/games/': typeof AuthenticatedGamesIndexRoute
  '/_authenticated/plays/': typeof AuthenticatedPlaysIndexRoute
  '/_authenticated/practice/': typeof AuthenticatedPracticeIndexRoute
  '/_authenticated/stats/': typeof AuthenticatedStatsIndexRoute
  '/_authenticated/plays/$playId/view': typeof AuthenticatedPlaysPlayIdViewRoute
  '/api/public/cron/daily': typeof ApiPublicCronDailyRoute
  '/api/public/film/claim': typeof ApiPublicFilmClaimRoute
  '/api/public/film/fail': typeof ApiPublicFilmFailRoute
  '/api/public/film/results': typeof ApiPublicFilmResultsRoute
  '/api/public/film/status': typeof ApiPublicFilmStatusRoute
  '/api/public/square/webhook': typeof ApiPublicSquareWebhookRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/plays/$playId/': typeof AuthenticatedPlaysPlayIdIndexRoute
  '/api/public/google/calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/locker/$token/calendar': typeof ApiPublicLockerTokenCalendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/achievements'
    | '/board'
    | '/calendar'
    | '/dashboard'
    | '/help'
    | '/kpi'
    | '/launch-qa'
    | '/locker'
    | '/lockerroom'
    | '/membership'
    | '/profile'
    | '/roster'
    | '/settings'
    | '/tools'
    | '/coach/$username'
    | '/drills/$drillId'
    | '/game-report/$token'
    | '/invite/$token'
    | '/join/$token'
    | '/library/$playId'
    | '/locker/$token'
    | '/share/$token'
    | '/library/'
    | '/drills/new'
    | '/film/$jobId'
    | '/film/new'
    | '/game/$gameId'
    | '/games/new'
    | '/plays/new'
    | '/practice/$planId'
    | '/review/$gameId'
    | '/stats/players'
    | '/stats/team'
    | '/share/play/$token'
    | '/drills/'
    | '/film/'
    | '/games/'
    | '/plays/'
    | '/practice/'
    | '/stats/'
    | '/plays/$playId/view'
    | '/api/public/cron/daily'
    | '/api/public/film/claim'
    | '/api/public/film/fail'
    | '/api/public/film/results'
    | '/api/public/film/status'
    | '/api/public/square/webhook'
    | '/api/public/stripe/webhook'
    | '/plays/$playId/'
    | '/api/public/google/calendar/callback'
    | '/api/public/locker/$token/calendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/achievements'
    | '/board'
    | '/calendar'
    | '/dashboard'
    | '/help'
    | '/kpi'
    | '/launch-qa'
    | '/locker'
    | '/lockerroom'
    | '/membership'
    | '/profile'
    | '/roster'
    | '/settings'
    | '/tools'
    | '/coach/$username'
    | '/drills/$drillId'
    | '/game-report/$token'
    | '/invite/$token'
    | '/join/$token'
    | '/library/$playId'
    | '/locker/$token'
    | '/share/$token'
    | '/library'
    | '/drills/new'
    | '/film/$jobId'
    | '/film/new'
    | '/game/$gameId'
    | '/games/new'
    | '/plays/new'
    | '/practice/$planId'
    | '/review/$gameId'
    | '/stats/players'
    | '/stats/team'
    | '/share/play/$token'
    | '/drills'
    | '/film'
    | '/games'
    | '/plays'
    | '/practice'
    | '/stats'
    | '/plays/$playId/view'
    | '/api/public/cron/daily'
    | '/api/public/film/claim'
    | '/api/public/film/fail'
    | '/api/public/film/results'
    | '/api/public/film/status'
    | '/api/public/square/webhook'
    | '/api/public/stripe/webhook'
    | '/plays/$playId'
    | '/api/public/google/calendar/callback'
    | '/api/public/locker/$token/calendar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/achievements'
    | '/_authenticated/board'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/help'
    | '/_authenticated/kpi'
    | '/_authenticated/launch-qa'
    | '/_authenticated/locker'
    | '/_authenticated/lockerroom'
    | '/_authenticated/membership'
    | '/_authenticated/profile'
    | '/_authenticated/roster'
    | '/_authenticated/settings'
    | '/_authenticated/tools'
    | '/coach/$username'
    | '/drills/$drillId'
    | '/game-report/$token'
    | '/invite/$token'
    | '/join/$token'
    | '/library/$playId'
    | '/locker/$token'
    | '/share/$token'
    | '/library/'
    | '/_authenticated/drills/new'
    | '/_authenticated/film/$jobId'
    | '/_authenticated/film/new'
    | '/_authenticated/game/$gameId'
    | '/_authenticated/games/new'
    | '/_authenticated/plays/new'
    | '/_authenticated/practice/$planId'
    | '/_authenticated/review/$gameId'
    | '/_authenticated/stats/players'
    | '/_authenticated/stats/team'
    | '/share/play/$token'
    | '/_authenticated/drills/'
    | '/_authenticated/film/'
    | '/_authenticated/games/'
    | '/_authenticated/plays/'
    | '/_authenticated/practice/'
    | '/_authenticated/stats/'
    | '/_authenticated/plays/$playId/view'
    | '/api/public/cron/daily'
    | '/api/public/film/claim'
    | '/api/public/film/fail'
    | '/api/public/film/results'
    | '/api/public/film/status'
    | '/api/public/square/webhook'
    | '/api/public/stripe/webhook'
    | '/_authenticated/plays/$playId/'
    | '/api/public/google/calendar/callback'
    | '/api/public/locker/$token/calendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CoachUsernameRoute: typeof CoachUsernameRoute
  DrillsDrillIdRoute: typeof DrillsDrillIdRoute
  GameReportTokenRoute: typeof GameReportTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
  JoinTokenRoute: typeof JoinTokenRoute
  LibraryPlayIdRoute: typeof LibraryPlayIdRoute
  LockerTokenRoute: typeof LockerTokenRoute
  ShareTokenRoute: typeof ShareTokenRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  SharePlayTokenRoute: typeof SharePlayTokenRoute
  ApiPublicCronDailyRoute: typeof ApiPublicCronDailyRoute
  ApiPublicFilmClaimRoute: typeof ApiPublicFilmClaimRoute
  ApiPublicFilmFailRoute: typeof ApiPublicFilmFailRoute
  ApiPublicFilmResultsRoute: typeof ApiPublicFilmResultsRoute
  ApiPublicFilmStatusRoute: typeof ApiPublicFilmStatusRoute
  ApiPublicSquareWebhookRoute: typeof ApiPublicSquareWebhookRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicGoogleCalendarCallbackRoute: typeof ApiPublicGoogleCalendarCallbackRoute
  ApiPublicLockerTokenCalendarRoute: typeof ApiPublicLockerTokenCalendarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/board': {
      id: '/_authenticated/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AuthenticatedBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kpi': {
      id: '/_authenticated/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof AuthenticatedKpiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/launch-qa': {
      id: '/_authenticated/launch-qa'
      path: '/launch-qa'
      fullPath: '/launch-qa'
      preLoaderRoute: typeof AuthenticatedLaunchQaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locker': {
      id: '/_authenticated/locker'
      path: '/locker'
      fullPath: '/locker'
      preLoaderRoute: typeof AuthenticatedLockerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lockerroom': {
      id: '/_authenticated/lockerroom'
      path: '/lockerroom'
      fullPath: '/lockerroom'
      preLoaderRoute: typeof AuthenticatedLockerroomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membership': {
      id: '/_authenticated/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof AuthenticatedMembershipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster': {
      id: '/_authenticated/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedRosterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/coach/$username': {
      id: '/coach/$username'
      path: '/coach/$username'
      fullPath: '/coach/$username'
      preLoaderRoute: typeof CoachUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drills/$drillId': {
      id: '/drills/$drillId'
      path: '/drills/$drillId'
      fullPath: '/drills/$drillId'
      preLoaderRoute: typeof DrillsDrillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-report/$token': {
      id: '/game-report/$token'
      path: '/game-report/$token'
      fullPath: '/game-report/$token'
      preLoaderRoute: typeof GameReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$playId': {
      id: '/library/$playId'
      path: '/library/$playId'
      fullPath: '/library/$playId'
      preLoaderRoute: typeof LibraryPlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locker/$token': {
      id: '/locker/$token'
      path: '/locker/$token'
      fullPath: '/locker/$token'
      preLoaderRoute: typeof LockerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/drills/': {
      id: '/_authenticated/drills/'
      path: '/drills'
      fullPath: '/drills/'
      preLoaderRoute: typeof AuthenticatedDrillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drills/new': {
      id: '/_authenticated/drills/new'
      path: '/drills/new'
      fullPath: '/drills/new'
      preLoaderRoute: typeof AuthenticatedDrillsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/film/': {
      id: '/_authenticated/film/'
      path: '/film'
      fullPath: '/film/'
      preLoaderRoute: typeof AuthenticatedFilmIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/film/$jobId': {
      id: '/_authenticated/film/$jobId'
      path: '/film/$jobId'
      fullPath: '/film/$jobId'
      preLoaderRoute: typeof AuthenticatedFilmJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/film/new': {
      id: '/_authenticated/film/new'
      path: '/film/new'
      fullPath: '/film/new'
      preLoaderRoute: typeof AuthenticatedFilmNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/game/$gameId': {
      id: '/_authenticated/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof AuthenticatedGameGameIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/': {
      id: '/_authenticated/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AuthenticatedGamesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/new': {
      id: '/_authenticated/games/new'
      path: '/games/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof AuthenticatedGamesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plays/': {
      id: '/_authenticated/plays/'
      path: '/plays'
      fullPath: '/plays/'
      preLoaderRoute: typeof AuthenticatedPlaysIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plays/new': {
      id: '/_authenticated/plays/new'
      path: '/plays/new'
      fullPath: '/plays/new'
      preLoaderRoute: typeof AuthenticatedPlaysNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/': {
      id: '/_authenticated/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof AuthenticatedPracticeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/$planId': {
      id: '/_authenticated/practice/$planId'
      path: '/practice/$planId'
      fullPath: '/practice/$planId'
      preLoaderRoute: typeof AuthenticatedPracticePlanIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/$gameId': {
      id: '/_authenticated/review/$gameId'
      path: '/review/$gameId'
      fullPath: '/review/$gameId'
      preLoaderRoute: typeof AuthenticatedReviewGameIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats/': {
      id: '/_authenticated/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof AuthenticatedStatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats/players': {
      id: '/_authenticated/stats/players'
      path: '/stats/players'
      fullPath: '/stats/players'
      preLoaderRoute: typeof AuthenticatedStatsPlayersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats/team': {
      id: '/_authenticated/stats/team'
      path: '/stats/team'
      fullPath: '/stats/team'
      preLoaderRoute: typeof AuthenticatedStatsTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/share/play/$token': {
      id: '/share/play/$token'
      path: '/share/play/$token'
      fullPath: '/share/play/$token'
      preLoaderRoute: typeof SharePlayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plays/$playId/': {
      id: '/_authenticated/plays/$playId/'
      path: '/plays/$playId'
      fullPath: '/plays/$playId/'
      preLoaderRoute: typeof AuthenticatedPlaysPlayIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plays/$playId/view': {
      id: '/_authenticated/plays/$playId/view'
      path: '/plays/$playId/view'
      fullPath: '/plays/$playId/view'
      preLoaderRoute: typeof AuthenticatedPlaysPlayIdViewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/daily': {
      id: '/api/public/cron/daily'
      path: '/api/public/cron/daily'
      fullPath: '/api/public/cron/daily'
      preLoaderRoute: typeof ApiPublicCronDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/film/claim': {
      id: '/api/public/film/claim'
      path: '/api/public/film/claim'
      fullPath: '/api/public/film/claim'
      preLoaderRoute: typeof ApiPublicFilmClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/film/fail': {
      id: '/api/public/film/fail'
      path: '/api/public/film/fail'
      fullPath: '/api/public/film/fail'
      preLoaderRoute: typeof ApiPublicFilmFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/film/results': {
      id: '/api/public/film/results'
      path: '/api/public/film/results'
      fullPath: '/api/public/film/results'
      preLoaderRoute: typeof ApiPublicFilmResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/film/status': {
      id: '/api/public/film/status'
      path: '/api/public/film/status'
      fullPath: '/api/public/film/status'
      preLoaderRoute: typeof ApiPublicFilmStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/square/webhook': {
      id: '/api/public/square/webhook'
      path: '/api/public/square/webhook'
      fullPath: '/api/public/square/webhook'
      preLoaderRoute: typeof ApiPublicSquareWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/calendar/callback': {
      id: '/api/public/google/calendar/callback'
      path: '/api/public/google/calendar/callback'
      fullPath: '/api/public/google/calendar/callback'
      preLoaderRoute: typeof ApiPublicGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/locker/$token/calendar': {
      id: '/api/public/locker/$token/calendar'
      path: '/api/public/locker/$token/calendar'
      fullPath: '/api/public/locker/$token/calendar'
      preLoaderRoute: typeof ApiPublicLockerTokenCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedBoardRoute: typeof AuthenticatedBoardRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedKpiRoute: typeof AuthenticatedKpiRoute
  AuthenticatedLaunchQaRoute: typeof AuthenticatedLaunchQaRoute
  AuthenticatedLockerRoute: typeof AuthenticatedLockerRoute
  AuthenticatedLockerroomRoute: typeof AuthenticatedLockerroomRoute
  AuthenticatedMembershipRoute: typeof AuthenticatedMembershipRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRosterRoute: typeof AuthenticatedRosterRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedDrillsNewRoute: typeof AuthenticatedDrillsNewRoute
  AuthenticatedFilmJobIdRoute: typeof AuthenticatedFilmJobIdRoute
  AuthenticatedFilmNewRoute: typeof AuthenticatedFilmNewRoute
  AuthenticatedGameGameIdRoute: typeof AuthenticatedGameGameIdRoute
  AuthenticatedGamesNewRoute: typeof AuthenticatedGamesNewRoute
  AuthenticatedPlaysNewRoute: typeof AuthenticatedPlaysNewRoute
  AuthenticatedPracticePlanIdRoute: typeof AuthenticatedPracticePlanIdRoute
  AuthenticatedReviewGameIdRoute: typeof AuthenticatedReviewGameIdRoute
  AuthenticatedStatsPlayersRoute: typeof AuthenticatedStatsPlayersRoute
  AuthenticatedStatsTeamRoute: typeof AuthenticatedStatsTeamRoute
  AuthenticatedDrillsIndexRoute: typeof AuthenticatedDrillsIndexRoute
  AuthenticatedFilmIndexRoute: typeof AuthenticatedFilmIndexRoute
  AuthenticatedGamesIndexRoute: typeof AuthenticatedGamesIndexRoute
  AuthenticatedPlaysIndexRoute: typeof AuthenticatedPlaysIndexRoute
  AuthenticatedPracticeIndexRoute: typeof AuthenticatedPracticeIndexRoute
  AuthenticatedStatsIndexRoute: typeof AuthenticatedStatsIndexRoute
  AuthenticatedPlaysPlayIdViewRoute: typeof AuthenticatedPlaysPlayIdViewRoute
  AuthenticatedPlaysPlayIdIndexRoute: typeof AuthenticatedPlaysPlayIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedBoardRoute: AuthenticatedBoardRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedKpiRoute: AuthenticatedKpiRoute,
  AuthenticatedLaunchQaRoute: AuthenticatedLaunchQaRoute,
  AuthenticatedLockerRoute: AuthenticatedLockerRoute,
  AuthenticatedLockerroomRoute: AuthenticatedLockerroomRoute,
  AuthenticatedMembershipRoute: AuthenticatedMembershipRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRosterRoute: AuthenticatedRosterRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedDrillsNewRoute: AuthenticatedDrillsNewRoute,
  AuthenticatedFilmJobIdRoute: AuthenticatedFilmJobIdRoute,
  AuthenticatedFilmNewRoute: AuthenticatedFilmNewRoute,
  AuthenticatedGameGameIdRoute: AuthenticatedGameGameIdRoute,
  AuthenticatedGamesNewRoute: AuthenticatedGamesNewRoute,
  AuthenticatedPlaysNewRoute: AuthenticatedPlaysNewRoute,
  AuthenticatedPracticePlanIdRoute: AuthenticatedPracticePlanIdRoute,
  AuthenticatedReviewGameIdRoute: AuthenticatedReviewGameIdRoute,
  AuthenticatedStatsPlayersRoute: AuthenticatedStatsPlayersRoute,
  AuthenticatedStatsTeamRoute: AuthenticatedStatsTeamRoute,
  AuthenticatedDrillsIndexRoute: AuthenticatedDrillsIndexRoute,
  AuthenticatedFilmIndexRoute: AuthenticatedFilmIndexRoute,
  AuthenticatedGamesIndexRoute: AuthenticatedGamesIndexRoute,
  AuthenticatedPlaysIndexRoute: AuthenticatedPlaysIndexRoute,
  AuthenticatedPracticeIndexRoute: AuthenticatedPracticeIndexRoute,
  AuthenticatedStatsIndexRoute: AuthenticatedStatsIndexRoute,
  AuthenticatedPlaysPlayIdViewRoute: AuthenticatedPlaysPlayIdViewRoute,
  AuthenticatedPlaysPlayIdIndexRoute: AuthenticatedPlaysPlayIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CoachUsernameRoute: CoachUsernameRoute,
  DrillsDrillIdRoute: DrillsDrillIdRoute,
  GameReportTokenRoute: GameReportTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
  JoinTokenRoute: JoinTokenRoute,
  LibraryPlayIdRoute: LibraryPlayIdRoute,
  LockerTokenRoute: LockerTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  SharePlayTokenRoute: SharePlayTokenRoute,
  ApiPublicCronDailyRoute: ApiPublicCronDailyRoute,
  ApiPublicFilmClaimRoute: ApiPublicFilmClaimRoute,
  ApiPublicFilmFailRoute: ApiPublicFilmFailRoute,
  ApiPublicFilmResultsRoute: ApiPublicFilmResultsRoute,
  ApiPublicFilmStatusRoute: ApiPublicFilmStatusRoute,
  ApiPublicSquareWebhookRoute: ApiPublicSquareWebhookRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicGoogleCalendarCallbackRoute: ApiPublicGoogleCalendarCallbackRoute,
  ApiPublicLockerTokenCalendarRoute: ApiPublicLockerTokenCalendarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
